### ISSUE TITLE
Unable to create custom formatter for Svelte 

### ISSUE THREAD

**Issue by siduck** [stevearc/conform.nvim#131]
```lua
local options = {

  -- custom formatter
  formatters = {
    svelte_fmt = {
      command = "prettier",
      args = { "--write", "--plugin", "prettier-plugin-svelte", vim.fn.expand "%" },
    },
  },

  formatters_by_ft = {
    svelte = { "svelte_fmt" },
  },
}

require("conform").setup(options)
  ```
  
![image](https://github.com/stevearc/conform.nvim/assets/59060246/11e33252-2f39-4b9b-9c7d-f6c5133b505c)

**Comment by siduck** [comment]
ok removed --write arg + i had 2 prettiers so removed the useless one, it works now

**Comment by siduck** [comment]
> Hi, I'm facing the same issue. I have globally installed prettier and prettier plugin svelte.

i installed with mason and had to manually set path

![image](https://github.com/stevearc/conform.nvim/assets/59060246/5512a558-649e-462f-8233-7c88d8bb6837)

**Comment by gitaarik** [comment]
Hey @siduck, how did you install Prettier with the `prettier-plugin-svelte` plugin through Mason?

And isn't there a way to configure the formatter without specifying the path? I want to be able to share my nvim setup with my friends without them having to know how to do this.

**Comment by siduck** [comment]
hi @gitaarik i installed it with npm, cd'ed into that mason local dir and installed the package. Ik this isnt a good solution. Its better if you ask on mason repo

> my friends without them having to know how to do this.

:laughing:

**Comment by siduck** [comment]
https://github.com/williamboman/mason.nvim/issues/161

**Comment by siduck** [comment]
any better solution? @williamboman

**Comment by gitaarik** [comment]
Ok, isn't it also just a matter of adding a mason registry package?

Something like this?

```yaml
---
name: prettier-plugin-svelte
description:  Format your svelte components using prettier.
homepage: https://github.com/sveltejs/prettier-plugin-svelte
licenses:
  - MIT
languages:
  - Svelte
categories:
  - Formatter

source:
  id: pkg:npm/prettier-plugin-svelte@3.2.2

bin:
  prettier: npm:prettier-plugin-svelte
```
