### ISSUE TITLE
Question: How might you configure `prettier` differently for `javascript` & `yaml` without conflicts?

### ISSUE THREAD

**Issue by aidenlangley** [stevearc/conform.nvim#81]
I'm curious how I would configure `prettier` to behave exclusively with `yaml` files. I'd like to add the arg: `--no-bracket-spacing` but only when `prettier` is working with `yaml` files.

The reason being `yamllint` defines a [rule](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.brackets) that specifies whether or not spaces are permissible inside brackets.

```yaml
rules:
  brackets:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 0
    min-spaces-inside-empty: -1
    max-spaces-inside-empty: -1
```

Something like...

```lua
formatters = {
  prettier_yaml = require("conform.formatters.prettier")
}
```

...perhaps?
